accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('singup/', views.SingUpView.as_view(), name="singup"),
]

homebudget/urls.py
from django.urls import path
from . import views

app_name = 'homebudget'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.CreateDataView.as_view(), name='create'),
    path('history', views.ListHomeView.as_view(),name="history"),
    path('delete/<int:pk>', views.DeleteDate, name='delete'),
    path('update/<int:pk>', views.UpdateDataView.as_view(),name="update"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('homebudget.urls')),
    path('accounts/', include('accounts.urls')),
    path("admin/", admin.site.urls),
]

#

accounts/models.py
from django.db import models

# Create your models here.

homebudget/models.py
from django.db import models
from django.utils import timezone

CATEGORY =( ("Food","食費"),("book","書籍"),("Favorite","趣味"),("subscribe","サブスク"),("Entertainment", "娯楽費"),("Work","経費") , ("income","収入"), ("other","その他"))

class HomoBudget(models.Model):
    category = models.CharField(max_length=100, choices=CATEGORY)
    price = models.IntegerField()
    content = models.CharField(max_length=100, default="")
    #日付の指定(https://docs.djangoproject.com/ja/5.2/ref/models/fields/#datefield )
    created_at = models.DateField()
    
    # user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    #名前から中身を推測できるようにするため
    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SingUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

homebudget/forms.py
from django import forms
from .models import HomoBudget

class CreateForm(forms.ModelForm):
    
    class Meta :
        model = HomoBudget
        fields = ["category", "price", "content", "created_at"]
        #widgets(読み：ウィジェット) imputタグの表示様式を指定する(https://docs.djangoproject.com/ja/5.2/ref/forms/widgets/)
        widgets = {
            #日付(時間なし)をカレンダーから選択できるようにしたい場合、DateInput,attrsはdateを使う(https://docs.djangoproject.com/ja/5.2/ref/forms/widgets/#dateinput )
            "created_at": forms.DateInput(
                attrs={"type": "date"}
            )
        }

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import SingUpForm

class SingUpView(CreateView):
    model = User
    form_class = SingUpForm
    template_name = 'accounts/singup.html'
    success_url = reverse_lazy('accounts:login')

homebudget/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.db.models import Sum , Avg # .models とは違う
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import HomoBudget
from .forms import CreateForm

def index(request):
    object_list = HomoBudget.objects.all()
    #incomes = HomoBudget.objects.filter(category = "income")
    aggregate_values = HomoBudget.objects.exclude(category='income').aggregate(payment = Sum("price"))
    income_values = HomoBudget.objects.filter(category='income').aggregate(incomes = Sum("price"))
    
    #支出の計算
    payment = aggregate_values["payment"] or 0
    income = income_values["incomes"] or 0
    total = income - payment
    
    if(payment > income * 0.5):
        isRed = True
    else:
        isRed = False
    
    # {}は辞書型
    return render(request, 
                "homebudget/index.html",
                {
                    "object_list":object_list,
                    "payment":aggregate_values["payment"],
                    "incomes":income_values["incomes"],
                    "total":total,
                    "isRed":isRed,
                }
                )

# 削除機能。jsのconfirm()を使うため関数を使用
def DeleteDate(request, pk):
    # 引数に入れた情報を元にオブジェクトを探す
    obj = get_object_or_404(HomoBudget, pk=pk)
    # 削除
    obj.delete()
    return redirect("homebudget:index")

class ListHomeView(LoginRequiredMixin,ListView):
    model = HomoBudget
    template_name = "homebudget/list.html"
    
    # def post(*):
        
    
class CreateDataView(LoginRequiredMixin,CreateView):
    model = HomoBudget
    form_class = CreateForm
    #fields = ["category", "price", "content", "created_at"] forms.pyを作ったため不使用
    template_name = "homebudget/create.html"
    success_url = reverse_lazy("homebudget:index")
    
class UpdateDataView(LoginRequiredMixin,UpdateView):
    model = HomoBudget
    form_class = CreateForm
    template_name = "homebudget/update.html"
    success_url = reverse_lazy("homebudget:index")

accounts/templates/accounts/singup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock title %}

{% block h1 %}アカウント作成{% endblock h1 %}


{% block content %}

<form method="post" class="m-4 p-4 bg-light border border-success rounded form form-group">
{% csrf_token %}
    <input class="form-control my-4" type="text" name="username" id="username" placeholder="ユーザー名">

    <input class="form-control mt-4" type="password" name="password1" id="pass" placeholder="パスワード">
    <input class="form-control mt-4" type="password" name="password2" id="pass" placeholder="パスワード(確認用)">
    <small class="mb-2 d-block text-start">※8文字以上</small>
    
    {% if form.errors %}
        <span class="mb-2 small text-danger d-block text-start">ユーザーIDかパスワードを打ち直してください</span>
    {% endif %}

    <button type="submit" class="btn btn-success">登録</button>
</form>

{% endblock content %}

homebudget/templates/homebudget/create.html
{% extends 'base.html' %}

{% block title %}
    作成ページ
{% endblock title %}
    

        
{% block content %}
<div class="d-flex justify-content-center ">
<div class=" card border border-success" style="width: 18rem;">
    <div class="card card-header bg-light text-center"><h3>作成ページ</h3></div>
    <div class="card-body">
    <form method="POST" class=" rounded form-group">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="作成">
        <a href="{% url 'homebudget:index' %}" class="btn btn-primary">戻る</a>
    </form>
    </div>

</div>
</div>


{% endblock content %}

homebudget/templates/homebudget/index.html
{% extends 'base.html' %}


{% block title %}ホーム{% endblock title %}

{% block h1 %}家計簿アプリ{% endblock h1 %}
{% block content %}

<main>
    <div class="row d-flex justify-content-center ">
            <div class=" card shadow col-md-8 border border-success">
                <div class="card-header py-4 ">
                    <h3 class="m-0 font-weight-bold text-success">今月の買い物ログ</h3>
                </div>
                <div class="card-body">
                <div class="table-responsive">
                    <div>
                        <h4>12月</h4>
                    </div>
                    <table id="my-table" class="table table-bordered table-striped table-sm table-hover table-fixed border border-success ">
                        <thead>
                            <tr class="text-center" >
                                <th data-id="price" scope="col" class="w-10 text-dark" aria-sort="ascending">金額</th>
                                <th data-id="category" scope="col" class="w-15 text-dark" >カテゴリー</th>
                                <th data-id="content" scope="col" class="w-30 text-dark text-wrap">内容</th>
                                <th data-id="created-at" scope="col" class="w-15 text-dark">作成日</th>
                                <th scope="col" class="text-dark">修正</th>
                                <th scope="col" class="text-dark">削除<th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for obj in  object_list %}
                            <tr class="table-success">
                                <td w-10>¥ {{obj.price}}</td>
                                <td class="w-15">{{obj.get_category_display}}</td>
                                <td class="w-30">{{obj.content}}</td>
                                <td class="text-center">{{obj.created_at|date:"m月d日"}}</td>
                                <td class="text-center"><a href="{% url 'homebudget:update' obj.pk %}" class="p-0 btn btn-success btn-sm">修正</a></td>
                                <td class="text-center"><a href="{% url 'homebudget:delete' obj.pk %}" class="p-0 btn btn-danger btn-sm text-nowrap" onclick="return confirm('本当に削除してもよろしいですか？')">削除</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                </div>

            </div>

        <div class="col-md-2">
            <div class="card shadow bg-light border border-success w-100">
                <div class="card-header">
                    <h4>今月の収支</h4>
                    <!-- ToDo: 桁数がわかりやすいように","をつけたい -->
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item  ">支出：¥{{payment}}</li> 
                    <li class="list-group-item">収入：¥{{incomes}}</li>
                
                    {% if isRed %}
                        <li class="list-group-item text-light bg-danger"> 赤字：¥{{total}}</li>
                    {% else %}
                        <li class="list-group-item text-light bg-info"> 健全：¥{{total}}</li>
                    {% endif %}
                    <!-- <small value="">支出 >= 収入 × 0.5</small> -->
                </ul>
            </div>

            <div class="card shadow bg-light border border-success w-100 my-4">
                <div class="card-header">
                    <h4>カテゴリ別支出</h4>
                    <!-- ToDo: 桁数がわかりやすいように","をつけたい -->
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item  ">食費：¥</li> 
                    <li class="list-group-item">書籍：¥</li>
                    <li class="list-group-item">サブスク：¥</li>
                </ul>
            </div>
        </div>
    </div>
</main>


{% endblock content %}

homebudget/templates/homebudget/list.html
{% extends 'base.html' %}


{% block title %}履歴{% endblock title %}


{% block h1 %}購入履歴{% endblock h1 %}
{% block content %}

<div class="d-flex justify-content-center">
    <table class=" table table-striped table-sm table-hover  border-success ">
        <thead>
            <!-- <caption>合計：¥</caption> -->
            <tr>
                <th scope="col" class="text-dark"">金額</th>
                <th scope="col" class="text-dark"">カテゴリー</th>
                <th scope="col" class="text-dark"">内容</th>
                <th scope="col" class="text-dark"">作成日</th>

            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for obj in  object_list%}
            <tr class="table-success">
                <td>¥ {{obj.price}}</td>
                <td>{{obj.get_category_display}}</td>
                <td>{{obj.content}}</td>
                <td>{{obj.created_at|date:"Y年m月d日(D)  "}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}
    

homebudget/templates/homebudget/update.html
{% extends 'base.html' %}

{% block title %}
    修正ページ
{% endblock title %}

    
{% block content %}


<div class="d-flex justify-content-center ">
<div class=" card border border-success" style="width: 18rem;">
    <div class="card card-header bg-light text-center"><h3>修正ページ</h3></div>
    <div class="card-body">
    <form method="POST" class=" rounded form-group">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="作成">
        <a href="{% url 'homebudget:index' %}" class="btn btn-primary">戻る</a>
    </form>
    </div>

</div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
        crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
    <nav class="navbar navbar-dark bg-success sticky-top">
        <div class="nav-bar d-flex flex-row">
            {% if request.user.is_authenticated %}
            <a class="nav-link mx-3 text-light" href="{% url 'homebudget:index' %}" >ホーム</a>
            <a class="nav-link mx-3 text-light" href="{% url 'homebudget:history' %}" >履歴</a>
            <a class="nav-link mx-3 text-light" href="{% url 'homebudget:create' %}" >作成</a>
            {% endif %}
        </div>

        <div class="nav-bar d-flex flex-row">
            
            {% if request.user.is_authenticated %}
                <label class="text-light" for="">ユーザー：{{request.user.username}}</label>
                <form method="POST" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <button class="text-light nav-link mx-3" type="submit">ログアウト</button>
                </form>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="text-light nav-link mx-3">ログイン</a>
                <a href="{% url 'accounts:singup' %}" class="text-light nav-link mx-3">会員登録</a>
            {% endif %}
                
        </div>
    </nav>
    </header>

    <div class="p-4 m-4 bg-body">
    <h1>{% block h1 %} {% endblock %}　</h1>
        {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>